/**
 * setup.js - 自动解密 Trae 配置并保存到 .env
 *
 * 支持四版本自动探测(按优先级):
 *   1. cn      - Trae CN 国内版
 *   2. solo    - TRAE SOLO CN 独立部署版
 *   3. sg      - Trae 国际版(明文 JSON)
 *   4. solo-sg - TRAE SOLO 国际版
 *
 * 若 .env 中已存在 TRAE_EDITION,则按指定版本优先尝试。
 *
 * Usage: node setup.js
 */

const fs = require('fs');
const path = require('path');
const {
  decryptAuthData,
  getTraeCNDataDir,
  getTraeSGDataDir,
  getTraeSoloCNDataDir,
  getTraeSoloSGDataDir,
} = require('./src/trae-decrypt');

const ENV_PATH = path.join(__dirname, '.env');

const EDITIONS = [
  { name: 'cn',      dirFn: getTraeCNDataDir,      host: 'https://api.trae.cn' },
  { name: 'solo',    dirFn: getTraeSoloCNDataDir,  host: 'https://api.trae.cn' },
  { name: 'sg',      dirFn: getTraeSGDataDir,      host: 'https://api.trae.ai' },
  { name: 'solo-sg', dirFn: getTraeSoloSGDataDir,  host: 'https://api.trae.ai' },
];

function readEnvValue(filePath, key) {
  try {
    if (!fs.existsSync(filePath)) return '';
    const content = fs.readFileSync(filePath, 'utf8');
    const regex = new RegExp(`^${key}=(.*)$`, 'm');
    const match = content.match(regex);
    return match ? match[1].trim() : '';
  } catch {
    return '';
  }
}

function readEnvFile(filePath) {
  const map = {};
  try {
    if (!fs.existsSync(filePath)) return map;
    const content = fs.readFileSync(filePath, 'utf8');
    for (const line of content.split('\n')) {
      const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (m) map[m[1]] = m[2];
    }
  } catch {}
  return map;
}

console.log('');
console.log('╔══════════════════════════════════════════╗');
console.log('║    Trae Local API - Auto Setup           ║');
console.log('╚══════════════════════════════════════════╝');
console.log('');

const preferredEdition = readEnvValue(ENV_PATH, 'TRAE_EDITION');
let orderedEditions = EDITIONS;
if (preferredEdition) {
  console.log(`[setup] Found existing TRAE_EDITION=${preferredEdition}, trying it first`);
  orderedEditions = [
    ...EDITIONS.filter(e => e.name === preferredEdition),
    ...EDITIONS.filter(e => e.name !== preferredEdition),
  ];
}

let authData = null;
let edition = null;
let apiHost = '';
let lastError = null;

for (const ed of orderedEditions) {
  try {
    console.log(`[setup] Trying ${ed.name} edition...`);
    authData = decryptAuthData(ed.dirFn());
    edition = ed.name;
    apiHost = authData.host || ed.host;
    console.log(`[setup] ${ed.name.toUpperCase()} edition decrypt success`);
    break;
  } catch (e) {
    console.log(`[setup] ${ed.name} edition failed: ${e.message}`);
    lastError = e;
  }
}

if (!authData) {
  console.error('');
  console.error('Failed to read Trae config. Ensure:');
  console.error('  1. Trae IDE is installed and logged in');
  console.error('  2. Config file exists at one of:');
  for (const ed of EDITIONS) {
    console.error(`     ${ed.name}: ${path.join(ed.dirFn(), 'globalStorage', 'storage.json')}`);
  }
  if (lastError) console.error(`  Last error: ${lastError.message}`);
  process.exit(1);
}

const existing = readEnvFile(ENV_PATH);
const merged = {
  ...existing,
  TRAE_EDITION: edition,
  TRAE_TOKEN: authData.token || '',
  TRAE_REFRESH_TOKEN: authData.refreshToken || '',
  TRAE_USER_ID: authData.userId || '',
  TRAE_API_HOST: apiHost,
  TRAE_TOKEN_EXPIRES: authData.expiredAt || '',
  TRAE_REFRESH_EXPIRES: authData.refreshExpiredAt || '',
  API_KEY: existing.API_KEY || process.env.API_KEY || 'trae-local-api',
  PORT: existing.PORT || process.env.PORT || '9220',
};

const envContent = [
  '# Auto-generated by setup.js',
  `# Generated at: ${new Date().toISOString()}`,
  ...Object.entries(merged).map(([k, v]) => `${k}=${v}`),
  '',
].join('\n');

fs.writeFileSync(ENV_PATH, envContent, 'utf8');

console.log('');
console.log('=== Setup Complete ===');
console.log('');
console.log(`Edition:        ${edition.toUpperCase()}`);
console.log(`UserID:         ${authData.userId}`);
console.log(`Username:       ${authData.account?.username || 'N/A'}`);
console.log(`Region:         ${authData.userRegion?.region || 'N/A'}`);
console.log(`Token:          ${authData.token ? authData.token.substring(0, 40) + '...' : 'N/A'}`);
console.log(`Token Expiry:   ${authData.expiredAt || 'N/A'}`);
console.log(`Refresh Expiry: ${authData.refreshExpiredAt || 'N/A'}`);
console.log(`API Host:       ${apiHost}`);
console.log(`Port:           ${merged.PORT}`);
console.log('');
console.log(`Saved to: ${ENV_PATH}`);
console.log('');
console.log('Start the server with:');
console.log('  npm start');
console.log('');