/**
 * auth.js - Authentication management
 *
 * Priority:
 * 1. TRAE_TOKEN from .env (pre-decrypted)
 * 2. Auto-decrypt from storage.json
 * 3. Manual TRAE_MANUAL_TOKEN
 */

const fs = require('fs');
const path = require('path');
const { decryptAuthData, getTraeCNDataDir, getTraeSGDataDir, getTraeSoloCNDataDir, getTraeSoloSGDataDir } = require('./trae-decrypt');

const ENV_PATH = path.join(__dirname, '..', '.env');

let authData = null;
let refreshMutex = false;

function initAuth(edition, manualToken) {
  if (process.env.TRAE_TOKEN) {
    console.log('[auth] Using TRAE_TOKEN from .env');
    authData = {
      token: process.env.TRAE_TOKEN,
      refreshToken: process.env.TRAE_REFRESH_TOKEN || null,
      userId: process.env.TRAE_USER_ID || '',
      expiredAt: process.env.TRAE_TOKEN_EXPIRES || null,
      refreshExpiredAt: process.env.TRAE_REFRESH_EXPIRES || null,
      host: process.env.TRAE_API_HOST || '',
    };
    _logAuth();
    return;
  }

  if (manualToken) {
    console.log('[auth] Using manual token from env');
    authData = { token: manualToken, refreshToken: null, userId: '' };
    return;
  }

  // Edition -> data dir resolver map (shared with setup.js fallback)
  const EDITION_DIRS = {
    cn: getTraeCNDataDir,
    solo: getTraeSoloCNDataDir,
    sg: getTraeSGDataDir,
    'solo-sg': getTraeSoloSGDataDir,
  };

  try {
    if (EDITION_DIRS[edition]) {
      authData = decryptAuthData(EDITION_DIRS[edition]());
      console.log(`[auth] Using ${edition.toUpperCase()} edition auth data (decrypted from storage.json)`);
    } else {
      authData = decryptAuthData(getTraeSGDataDir());
      console.log('[auth] Using SG edition auth data');
      edition = 'sg';
    }
    _logAuth();
    process.env.TRAE_EDITION = edition;
    _saveEnv(edition);
  } catch (err) {
    // Specified edition failed — auto-detect across all editions
    console.log(`[auth] ${edition} edition failed: ${err.message}`);
    console.log('[auth] Auto-detecting installed Trae edition...');
    for (const [name, dirFn] of Object.entries(EDITION_DIRS)) {
      try {
        authData = decryptAuthData(dirFn());
        edition = name;
        console.log(`[auth] Using ${name.toUpperCase()} edition auth data (auto-detected)`);
        break;
      } catch {}
    }
    if (!authData) {
      console.error('[auth] Failed to load auth data from any Trae edition');
      console.error('[auth] Ensure a Trae IDE is installed and logged in, or run: npm run setup');
      throw err;
    }
    _logAuth();
    process.env.TRAE_EDITION = edition;
    _saveEnv(edition);
  }
}

function _logAuth() {
  if (authData.token) console.log(`[auth] Token: ${authData.token.substring(0, 40)}...`);
  if (authData.userId) console.log(`[auth] UserID: ${authData.userId}`);
  if (authData.expiredAt) console.log(`[auth] Token expires: ${authData.expiredAt}`);
}

function readEnvFile(filePath) {
  const map = {};
  try {
    if (!fs.existsSync(filePath)) return map;
    const content = fs.readFileSync(filePath, 'utf8');
    for (const line of content.split('\n')) {
      const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
      if (m) map[m[1]] = m[2];
    }
  } catch {}
  return map;
}

function _saveEnv(edition) {
  try {
    const existing = readEnvFile(ENV_PATH);
    const merged = {
      ...existing,
      TRAE_EDITION: edition,
      TRAE_TOKEN: authData.token || '',
      TRAE_REFRESH_TOKEN: authData.refreshToken || '',
      TRAE_USER_ID: authData.userId || '',
      TRAE_API_HOST: authData.host || existing.TRAE_API_HOST || '',
      TRAE_TOKEN_EXPIRES: authData.expiredAt || '',
      TRAE_REFRESH_EXPIRES: authData.refreshExpiredAt || '',
      API_KEY: existing.API_KEY || process.env.API_KEY || 'trae-local-api',
      PORT: existing.PORT || process.env.PORT || '9220',
    };
    const lines = ['# Auto-generated by dsh-trae-api', ...Object.entries(merged).map(([k, v]) => `${k}=${v}`)];
    fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n', 'utf8');
    console.log(`[auth] Saved credentials to ${ENV_PATH}`);
  } catch (e) {
    console.warn(`[auth] Could not save .env: ${e.message}`);
  }
}

function getToken() { return authData ? authData.token : null; }
function getUserId() { return authData ? authData.userId : null; }
function getRefreshToken() { return authData ? authData.refreshToken : null; }

function needsRefresh() {
  if (!authData || !authData.expiredAt) return false;
  const expiry = new Date(authData.expiredAt).getTime();
  return Date.now() >= expiry - 30 * 60 * 1000;
}

async function refreshToken() {
  if (refreshMutex) return;
  refreshMutex = true;
  try {
    const rt = authData.refreshToken;
    if (!rt) { console.error('[auth] No refreshToken'); return; }

    const refreshHost = authData.host || process.env.TRAE_API_HOST || 'https://api.trae.cn';

    console.log('[auth] Refreshing token...');
    const resp = await fetch(`${refreshHost}/cloudide/api/v3/trae/oauth/ExchangeToken`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ClientID: 'ono9krqynydwx5',
        RefreshToken: rt,
        ClientSecret: '-',
        UserID: authData.userId || '',
      }),
    });

    if (!resp.ok) {
      console.error(`[auth] Refresh failed: ${resp.status} ${await resp.text()}`);
      return;
    }

    const data = await resp.json();
    if (data.Result) {
      authData.token = data.Result.Token;
      authData.refreshToken = data.Result.RefreshToken || authData.refreshToken;
      authData.expiredAt = data.Result.TokenExpireAt
        ? new Date(data.Result.TokenExpireAt).toISOString() : authData.expiredAt;
      console.log('[auth] Token refreshed');
      _saveEnv(process.env.TRAE_EDITION || 'cn');
    }
  } catch (err) {
    console.error(`[auth] Refresh error: ${err.message}`);
  } finally {
    refreshMutex = false;
  }
}

module.exports = { initAuth, getToken, getUserId, getRefreshToken, needsRefresh, refreshToken };